Make BMI2 disabled by default
AntelopeIO/bn256 pull request #12
Opened 2022-12-27 15:00 UTC by huangminghuang

The PR addresses Isuue #11 to disable BMI2 instruction by default.

2023-01-05 17:53 UTC, spoonincode requested changes
I don't believe this works as is because the compile flags still end up with `-mbmi2` meaning that the compiler is free to make use of BMI2 instructions. And indeed, the optimizer seemed to recognize the pattern and did just that.

```
_ZN5bn25615mulx_u64_nobmi2EmmPm():
    c6c0:       48 89 d1                mov    %rdx,%rcx
    c6c3:       48 89 f2                mov    %rsi,%rdx
    c6c6:       c4 e2 cb f6 ff          mulx   %rdi,%rsi,%rdi
    c6cb:       48 89 39                mov    %rdi,(%rcx)
    c6ce:       48 89 f0                mov    %rsi,%rax
    c6d1:       c3                      ret
    c6d2:       66 2e 0f 1f 84 00 00    cs nopw 0x0(%rax,%rax,1)
    c6d9:       00 00 00
    c6dc:       0f 1f 40 00             nopl   0x0(%rax)
```

```
_ZN5bn25613mulx_u64_bmi2EmmPm():
    4830:       48 89 d1                mov    %rdx,%rcx
    4833:       48 89 fa                mov    %rdi,%rdx
    4836:       c4 e2 cb f6 fe          mulx   %rsi,%rsi,%rdi
    483b:       48 89 39                mov    %rdi,(%rcx)
    483e:       48 89 f0                mov    %rsi,%rax
    4841:       c3                      ret
    4842:       66 66 2e 0f 1f 84 00    data16 cs nopw 0x0(%rax,%rax,1)
    4849:       00 00 00 00
    484d:       0f 1f 00                nopl   (%rax)
```

2023-02-10 20:13 UTC, spoonincode commented
This seems to have a substantial performance degradation compared to main. It's nearly 20% slower on the same hardware with gcc12, for the `scaler_base_multi` tests. It's significantly slower than just running main with the BMI2 code disabled (that only seems to have a ~3% hit for me)

2023-02-16 03:12 UTC, spoonincode approved these changes

2023-02-16 16:00 UTC, heifner approved these changes

2023-02-16 17:06 UTC, merged