Curve lattice twist optate
AntelopeIO/bn256 pull request #2
Opened 2022-09-19 20:22 UTC by plabanca

2022-09-22 03:51 UTC, spoonincode commented
bn256_test.cpp appears to need an `#include <memory>` otherwise std::unique_ptr isn't found when using libstdc++ 12 (gcc12)

2022-09-26 17:45 UTC, linh2931 requested changes

2022-09-26 17:45 UTC, linh2931 commented on src/curve.cpp
> +    static constexpr gfp curve_b {3};
Our code base uses 3 spaces for indentation. Please conform to it. This comment applies to all the files.

lattice.h has very long spaces (9) in some statements.

2022-09-26 17:45 UTC, linh2931 commented on src/lattice.cpp
> +
Add the missing comment `// Calculate closest vector in lattice to <k,0,0,...> with Babai's rounding.`

2022-09-26 17:45 UTC, linh2931 commented on src/lattice.cpp
> +
Remove empty line

2022-09-26 17:45 UTC, linh2931 commented on src/lattice.cpp
> +                out[i] = out[i] + temp;
Change to `out[i] += temp;`

2022-09-26 17:45 UTC, linh2931 commented on src/lattice.cpp
> +            const auto j = &x - &decomp[0];
Can` j` use explicit value rather than address manipluation?

2022-09-26 17:45 UTC, linh2931 commented on src/optate.cpp
> +        t2.mul(rc.out_.y_, j);
Should `rc.out_.y_` be `r.y_`?

2022-09-26 17:45 UTC, linh2931 commented on src/optate.cpp
> +        rc.out_.y_.sub(rc.out_.y_, t);
I can't find where those came from.

2022-09-26 17:45 UTC, linh2931 commented on src/optate.cpp
> +
remove empty line

2022-09-26 17:45 UTC, linh2931 commented on src/curve.h
> +
Add the comments from the original file.

2022-09-26 17:45 UTC, linh2931 commented on src/curve.cpp
> +        gfp_add(t, a.z_, b.z_);       // t11
Align the comment

2022-09-26 17:45 UTC, linh2931 commented on src/curve.cpp
> +        }
Why the following code from the original was missing?

 ```
 zInv := &gfP{}
  zInv.Invert(&c.z)

  t, zInv2 := &gfP{}, &gfP{}
  gfpMul(t, &c.y, zInv)
  gfpMul(zInv2, zInv, zInv)

  gfpMul(&c.x, &c.x, zInv2)
  gfpMul(&c.y, t, zInv2)

  c.z = *newGFp(1)
  c.t = *newGFp(1)
```

2022-09-26 17:45 UTC, linh2931 commented on src/curve.cpp
> +        std::stringstream ss;
You can just use std::string for ss and use std::string's operations.

2022-09-26 17:45 UTC, linh2931 commented on src/curve.cpp
> +    std::string curve_point::string() {
Why was not this function placed in the beginning as the original one?

2022-09-26 17:45 UTC, linh2931 commented on src/twist.h
> +
Add the comments from the original.

2022-09-26 17:45 UTC, linh2931 commented on src/twist.cpp
> +        gfp2 z12{}, z22{}, u1{}, u2{}, t{}, s1{}, s2{}, h{}, i{}, j{}, r{}, v{}, t4{}, t6{};
It would be better to declare variables next to their first uses.

2022-09-26 17:45 UTC, linh2931 commented on src/twist.cpp
> +        t4.square(t);      // t12
align the comment

2022-09-26 17:45 UTC, linh2931 commented on src/twist.cpp
> +        gfp2 a2{}, b{}, c{}, t{}, t2{}, d{}, e{}, f{};
It might be better keep the cases  of the original so you don't need to use `a2`

2022-09-26 17:45 UTC, linh2931 commented on src/twist.cpp
> +
Remove empty line. This applies to other functions too.

2022-09-26 17:45 UTC, linh2931 commented on src/twist.cpp
> +    std::string twist_point::string() {
The comment of curve.cpp applies to here.

2022-09-26 23:14 UTC, plabanca commented on src/curve.cpp
> +    static constexpr gfp curve_b {3};
Resolved with commit: https://github.com/AntelopeIO/bn256/pull/2/commits/43addb83e26bc0f0a281f4b451354925da063af3

2022-09-27 06:13 UTC, plabanca commented on src/optate.cpp
> +        t2.mul(rc.out_.y_, j);
Yes, it should:

	t := (&gfP2{}).Sub(V, &rOut.x)
	t.Mul(t, L1)
	**t2 := (&gfP2{}).Mul(&r.y, J)**

2022-09-27 06:13 UTC, plabanca commented on src/optate.cpp
> +        rc.out_.y_.sub(rc.out_.y_, t);
**optate.go: lines 73-74:**

rOut.y.Sub(D, &rOut.x).Mul(&rOut.y, E)
**t := (&gfP2{}).Add(C, C)
t.Add(t, t).Add(t, t)**
rOut.y.Sub(&rOut.y, t)

2022-09-27 15:01 UTC, linh2931 commented on src/optate.cpp
> +        rc.out_.y_.sub(rc.out_.y_, t);
I must have misread.

2022-09-27 15:03 UTC, linh2931 approved these changes

2022-09-27 15:18 UTC, merged