remove boost
AntelopeIO/bn256 pull request #6
Opened 2022-10-27 18:01 UTC by huangminghuang

This PR
- removes boost dependency,
- optimizes the basic 256 bit integer arithmetic operations with gcc overflow or clang carry intrinsics,
- adds a new int512_t class,
- adds `pairing_check()`, `g1_add()`, `g1_scalar_mul()` to be used by leap,
- avoid any dynamic memory allocation,
- refactor cmake for more host system detection,
- add github actions for CI.

2022-10-30 15:44 UTC, linh2931 requested changes

2022-10-30 15:44 UTC, linh2931 commented on .github/workflows/actions.yml
> +            vm_image: ubuntu-20.04
What about ubuntu-22.04, assuming we can ignore ubuntu-18.04?

2022-10-30 15:44 UTC, linh2931 commented on include/bn256.h
> +// uint255_t should be a 255 bits integer in little endian format
Just curious why not 256 bits? Can you add some comments about it?

2022-10-30 15:44 UTC, linh2931 commented on .github/workflows/actions.yml
> +            vm_image: ubuntu-20.04
What about ubuntu-22.04? It's better to make sure newer OS not broken. 18.04 can be ignored.

2022-10-30 15:44 UTC, linh2931 commented on include/bn256.h
> +/// pairing_check calculates the Optimal Ate pairing for for a set of points.
Remove `for` from `for for`

2022-10-30 15:44 UTC, linh2931 commented on include/bn256.h
> +/// @return -1 for unmarshal error, 0 for success
It would be nice to return `alt_bn128_error` as defined in `libfc/crypto/alt_bn128.hpp`. But it can be done in the FC adaption task.

2022-10-30 15:44 UTC, linh2931 commented on .github/workflows/actions.yml
> +      - name: 'install OpenSSL (ubuntu)'
Do we still need OpenSSL?

2022-10-30 15:44 UTC, linh2931 commented on src/gfp_generic.h
>     return gfp_carry(c, carry);
`gfp_carry` is defined as
`constexpr array<uint64_t, 4> gfp_carry(const array<uint64_t, 4>& a, uint64_t head)`

Is `carry` as `bool` OK for `head`?

2022-10-30 15:44 UTC, linh2931 commented on src/int512.h
> +      for (int i = 0; i < 7; ++i) {
Should 8.

2022-10-31 14:00 UTC, huangminghuang commented on .github/workflows/actions.yml
> +            vm_image: ubuntu-20.04
updated with 22.04 config

2022-10-31 14:00 UTC, huangminghuang commented on include/bn256.h
> +// uint255_t should be a 255 bits integer in little endian format
The original go library restricts it to a 256 bits positive integer, which is essentially 255 bits unsigned int. I don't know much about the math behind it . I just chose a type name that could truly reflect the value range.

2022-10-31 14:00 UTC, huangminghuang commented on include/bn256.h
> +/// pairing_check calculates the Optimal Ate pairing for for a set of points.
fixed

2022-10-31 14:00 UTC, huangminghuang commented on include/bn256.h
> +/// @return -1 for unmarshal error, 0 for success
I didn't do that simply because our host function implementation just ignore all different error conditions and just return a single error code to user. I don't think it's worthwhile to map those error code to alt_bn128_error and just  to throw the information away eventually.

2022-10-31 14:00 UTC, huangminghuang commented on src/gfp_generic.h
>     return gfp_carry(c, carry);
Yes, the parameter is passed by value and it could be implicitly converted.

2022-11-01 18:16 UTC, linh2931 approved these changes

2022-11-01 18:24 UTC, merged